name: projectree
description: ProjecTree mobile app - Digital hub for college students
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter & UI
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  photo_view: ^0.14.0

  # Navigation & State
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Supabase
  supabase_flutter: ^2.5.6

  # Networking & JSON
  dio: ^5.4.0
  retrofit: ^4.0.3
  http: ^1.1.0
  json_annotation: ^4.8.1

  # Realtime & Chat
  socket_io_client: ^2.0.3+1

  # Media & Image
  image_picker: ^1.1.2

  # Storage & Local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.0
  url_launcher: ^6.3.0
  app_links: ^3.4.5
  url_strategy: ^0.2.0

  # AI
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
