name: projectree_flutter
description: ProjecTree mobile app - Digital hub for college students
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Supabase
  supabase_flutter: ^2.3.4

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Socket.IO for real-time messaging
  socket_io_client: ^2.0.3+1

  # UI & Navigation
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

  # Image handling
  image_picker: ^1.0.4
  photo_view: ^0.14.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Utils
  intl: ^0.19.0
  timeago: ^3.6.0
  url_launcher: ^6.2.2

  # Icons & Animations
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_animate: ^4.3.0

  # Deep linking for OAuth
  app_links: ^3.4.5

  # URL strategy for web
  url_strategy: ^0.2.0

  # AI Integration - Google Generative AI
  google_generative_ai: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
